name: ASP.NET Core CI with Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./EventsWebApp.API/Dockerfile
        push: true
        tags: d1amond9/events-web-app-api:latest
      
    - name: Run tests in Docker
      run: |
        docker run -d -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} --name events-web-app-api d1amond9/events-web-app-api:latest

    - name: Wait for the application to be ready
      run: |
        for i in {1..30}; do
          if curl --silent --fail http://localhost:8080; then
            echo "Application is running."
            exit 0
          fi
          echo "Waiting for application to start..."
          sleep 2
        done
        exit 1
        
    - name: Complete workflow
      run: echo "Workflow completed successfully!"
