name: ASP.NET Core CI with Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./EventsWebApp.API/Dockerfile
        push: true
        tags: d1amond9/events-web-app-api:latest
      
    - name: Run tests in Docker
      run: |
        docker run --rm -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} d1amond9/events-web-app-api:latest dotnet test --no-build --verbosity normal

    - name: Complete workflow
      run: echo "Workflow completed successfully!"

    - name: Exit with success
      run: exit 0
